/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Crist
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jDesktopPanePricipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVenda = new javax.swing.JMenu();
        menuCadastros = new javax.swing.JMenu();
        menuCadastrosCliente = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuCadastrosProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuConsultasCliente = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MenuConsultasProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuConsultasUsuarios = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        MenuRelatoriosVendas = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        MenuRelatoriosCliente = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        MenuRelatoriosProdutos = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysVenda");
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SysVendahome.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jDesktopPanePricipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePricipalLayout = new javax.swing.GroupLayout(jDesktopPanePricipal);
        jDesktopPanePricipal.setLayout(jDesktopPanePricipalLayout);
        jDesktopPanePricipalLayout.setHorizontalGroup(
            jDesktopPanePricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePricipalLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jDesktopPanePricipalLayout.setVerticalGroup(
            jDesktopPanePricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePricipalLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );

        jToolBar1.setRollover(true);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1095, 736));

        menuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_form_add.png"))); // NOI18N
        menuVenda.setText("VENDA");
        menuVenda.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVendaMouseClicked(evt);
            }
        });
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuVenda);

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_form_edit.png"))); // NOI18N
        menuCadastros.setText("CADASTROS");
        menuCadastros.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        menuCadastrosCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadastrosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_add.png"))); // NOI18N
        menuCadastrosCliente.setText("Cliente");
        menuCadastrosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastrosCliente);
        menuCadastros.add(jSeparator6);

        menuCadastrosProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadastrosProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart_add.png"))); // NOI18N
        menuCadastrosProduto.setText("Produto");
        menuCadastrosProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosProdutoActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastrosProduto);
        menuCadastros.add(jSeparator1);

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computer_key.png"))); // NOI18N
        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCadastros.add(jMenuItem1);

        jMenuBar1.add(menuCadastros);

        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder_table.png"))); // NOI18N
        menuConsultas.setText("CONSULTAS");
        menuConsultas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuConsultas.add(jSeparator4);

        menuConsultasCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group.png"))); // NOI18N
        menuConsultasCliente.setText("Cliente");
        menuConsultasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasClienteActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasCliente);
        menuConsultas.add(jSeparator5);

        MenuConsultasProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.png"))); // NOI18N
        MenuConsultasProduto.setText("Produto");
        MenuConsultasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultasProdutoActionPerformed(evt);
            }
        });
        menuConsultas.add(MenuConsultasProduto);
        menuConsultas.add(jSeparator2);

        menuConsultasUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computer_key.png"))); // NOI18N
        menuConsultasUsuarios.setText("Usuario");
        menuConsultasUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasUsuariosActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasUsuarios);

        jMenuBar1.add(menuConsultas);

        MenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/printer.png"))); // NOI18N
        MenuRelatorios.setText("RELATÓRIOS");
        MenuRelatorios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        MenuRelatoriosVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart_put.png"))); // NOI18N
        MenuRelatoriosVendas.setText("Vendas");
        MenuRelatorios.add(MenuRelatoriosVendas);
        MenuRelatorios.add(jSeparator7);

        MenuRelatoriosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group.png"))); // NOI18N
        MenuRelatoriosCliente.setText("Clientes");
        MenuRelatoriosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatoriosClienteActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatoriosCliente);
        MenuRelatorios.add(jSeparator8);

        MenuRelatoriosProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.png"))); // NOI18N
        MenuRelatoriosProdutos.setText("Produtos");
        MenuRelatorios.add(MenuRelatoriosProdutos);

        jMenuBar1.add(MenuRelatorios);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_in.png"))); // NOI18N
        menuSair.setText("SAIR");
        menuSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePricipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePricipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosClienteActionPerformed
        CadastrosClientes ccliente = new CadastrosClientes();
        jDesktopPanePricipal.add(ccliente);
        ccliente.setVisible(true);
        try {
            ccliente.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCadastrosClienteActionPerformed

    private void menuConsultasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasClienteActionPerformed
        ConsultasClientes cclientes = new ConsultasClientes();
        try {
            jDesktopPanePricipal.add(cclientes);
            cclientes.setVisible(true);
            cclientes.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuConsultasClienteActionPerformed

    private void MenuConsultasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultasProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultasProdutoActionPerformed

    private void MenuRelatoriosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatoriosClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatoriosClienteActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
//       
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadastrosProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosProdutoActionPerformed
        CadastrosProduto cproduto = new CadastrosProduto();
        jDesktopPanePricipal.add(cproduto);
        cproduto.setVisible(true);
        try {
            cproduto.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCadastrosProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastrosUsuario cusuario = new CadastrosUsuario();
        jDesktopPanePricipal.add(cusuario);
        cusuario.setVisible(true);
        try {
            cusuario.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        //
    }//GEN-LAST:event_menuVendaActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1)
        {
           TelaLogin login = new TelaLogin();
           login.setVisible(true);
           login.setExtendedState(TelaLogin.MAXIMIZED_BOTH);
           dispose();
        }
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVendaMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1)
        {
            Venda venda = new Venda();
            jDesktopPanePricipal.add(venda);
            venda.setVisible(true);
            try {
                venda.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaHome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuVendaMouseClicked

    private void menuConsultasUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasUsuariosActionPerformed
        ConsultasUsuarios cusuarios = new ConsultasUsuarios();
        try {
            jDesktopPanePricipal.add(cusuarios);
            cusuarios.setVisible(true);
            cusuarios.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuConsultasUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuConsultasProduto;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenuItem MenuRelatoriosCliente;
    private javax.swing.JMenuItem MenuRelatoriosProdutos;
    private javax.swing.JMenuItem MenuRelatoriosVendas;
    private javax.swing.JDesktopPane jDesktopPanePricipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuCadastrosCliente;
    private javax.swing.JMenuItem menuCadastrosProduto;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasCliente;
    private javax.swing.JMenuItem menuConsultasUsuarios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuVenda;
    // End of variables declaration//GEN-END:variables
}
